In [2]:
import numpy as np

np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.arange(16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.random.random((512,24))

array([[0.2685238 , 0.14185139, 0.96288558, ..., 0.39947555, 0.94900112,
        0.92898775],
       [0.33589736, 0.39321488, 0.83196712, ..., 0.78543124, 0.80103961,
        0.48784467],
       [0.59131047, 0.05800702, 0.7631559 , ..., 0.82100069, 0.92247281,
        0.53121262],
       ...,
       [0.49991046, 0.76932469, 0.69229912, ..., 0.69040731, 0.60743706,
        0.58774657],
       [0.29067141, 0.32951373, 0.93030137, ..., 0.38324424, 0.8456398 ,
        0.54510798],
       [0.03287595, 0.6917237 , 0.57879656, ..., 0.32845415, 0.62123944,
        0.02335921]])

In [18]:
np.arange(9) * np.arange(9)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.ones((3,3)) @ np.eye(3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
a = np.ones((4,4))
i = np.eye(4)
a.dot(i)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
import numpy as np

a = np.array([[1295,1325,9.63],
              [1305,1335,9.73]])
b = np.array([190,200,40000])

a @ b

array([896250., 904150.])

In [40]:
(a * b).sum(axis=1)

array([896250., 904150.])

In [42]:
np.arange(10) * np.ones(1) * 3

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [45]:
np.arange(81).reshape((9,9))[]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [57]:
np.arange(81).reshape((9,9))[:, :]

array([[63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [ ]:
a = [ 1305, 13]